### PR TITLE
Mentionify only relevant docs or pages

### PR DESCRIPTION
**Pull request by ashmaroli**
- add a check to ensure that the content passed to `HTML::Pipeline::MentionFilter` contains the given `mention_username_pattern`.
- this avoids having to process docs or pages that contain `@` only in the `<head>` element

### CODE REVIEW

**Comment by pathawks** [comment]
Do you have any benchmarks?

**Comment by ashmaroli** [comment]
> Do you have any benchmarks?

Not really, but Jekyll's official docs build *faster* with this patch..

**Comment by oe** [comment]
@pathawks As far as my own flamegraph tests with the docs go, emojify and mentionify always take up a significant chunk of processing time, so I think anything to slim that down is a good idea.

**Comment by DirtyF** [comment]
Build time seems to take 1s less with this patch on our docs on macOS.

**Comment by ashmaroli** [comment]
Based on `script/stackprof`at Jekyll:
```
TOTAL    (pct)     SAMPLES    (pct)     FRAME
  954  (31.2%)          0    (0.0%)     Jekyll::Mentions.mentionify   (jekyll-mentions-1.2.0)
  843  (19.1%)         10    (0.2%)     Jekyll::Mentions.mentionify   (this-PR)
```

**Comment by ashmaroli** [comment]
ping: Travis needs a restart..

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
